---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: Check docker-compose
    command: docker-compose -v
    register: output
    failed_when: "'FAILED' in output.stderr"

  - name: Prompt
    pause: prompt="Please choose one of the following - deploy|scale|terminate"
    register: arg1

  - name: Prompt2
    pause: prompt="Provide scaling capacity [ scale >=1 ]"
    when: arg1.user_input == "scale"
    register: arg2

  - name: Get git repository
    git: 
      repo=https://github.com/ctepx25/elk.git
      dest=/tmp/elk
    when: arg1.user_input == "deploy"

  - name: Create environment
    command: docker-compose -f /tmp/elk/docker-compose.yml up --scale elasticsearch2=2 -d
    register: dockeroutput
    when: arg1.user_input == "deploy"  

  - name: Install dependences
    shell: docker exec -t nginx-filebeat bash -c 'apt-get update;apt-get install curl nginx -y'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines
    when: output.stdout is defined

  - name: Install Filebeat 
    shell: docker exec -t nginx-filebeat bash -c 'curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.3.0-amd64.deb;dpkg -i filebeat-6.3.0-amd64.deb'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines
    when: output.stdout is defined

  - name: Copy filebeat.yml
    shell: docker cp /tmp/elk/filebeat.yml nginx-filebeat:/etc/filebeat/filebeat.yml
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines
    when: output.stdout is defined

  - name: Restart NGINX
    shell: docker exec -t nginx-filebeat bash -c '/etc/init.d/nginx restart'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines
    when: output.stdout is defined

  - name: Restart FILEBEAT
    shell: docker exec nginx-filebeat bash -c 'chown root:root /etc/filebeat/filebeat.yml;exec -c service filebeat start'
    register: output
    when: arg1.user_input == "deploy"
  - debug: var=output.stdout_lines
    when: output.stdout is defined


  - name: Terminate environemnt
    command: docker-compose -f /tmp/elk/docker-compose.yml down
    register: output
    when: arg1.user_input == "terminate"  
  - debug: var=output.stdout_lines
    when: output.stdout is defined

  - name: Scale elasticsearch cluster
    command: docker-compose -f /tmp/elk/docker-compose.yml scale  elasticsearch2={{arg2.user_input|int - 1 }}
    register: output
    when: 
      - arg1.user_input == "scale"
      - arg2.user_input >= 1
  - debug: var=output.stdout_lines
    when: output.stdout is defined
