---
- hosts: localhost
  gather_facts: no
  tasks:

  - name: Get git
    git: 
      repo=https://github.com/ctepx25/elk.git
      dest=/tmp/elk

  - name: Check if docker is installed
    shell: which docker-compose
    register: output1

  - name: Create environment
    command: docker-compose -f /tmp/elk/docker-compose.yml up -d
    register: dockeroutput
    when: output1.rc == 0

  - name: Install dependences
    shell: docker exec -t nginx-filebeat bash -c 'apt-get update;apt-get install curl -y'
    register: output
  - debug: msg={{output.stdout}}

  - name: Install Filebeat
    shell: docker exec -t nginx-filebeat bash -c 'curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.3.0-amd64.deb;dpkg -i filebeat-6.3.0-amd64.deb'
    register: output
  - debug: msg={{output.stdout}}

  - name: Copy filebeat.yml
    shell: docker cp ./filebeat.yml nginx-filebeat:/etc/filebeat/filebeat.yml
    register: output
  - debug: msg={{output.stdout}}

  - name: Restart NGINX
    shell: docker exec -t nginx-filebeat bash -c '/etc/init.d/nginx restart'
    register: output
  - debug: msg={{output.stdout}}

  - name: Restart FILEBEAT
    shell: docker exec -t nginx-filebeat bash -c 'chown root:root /etc/filebeat/filebeat.yml;/etc/init.d/filebeat start'
    register: output
  - debug: msg={{output.stdout}}

