---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Install dependences
      shell: docker exec -t nginx-filebeat bash -c 'apt-get update;apt-get install apt-transport-https wget gnupg gnupg2 gnupg1 nginx openjdk-8-jdk -y'
      register: output
    - debug: msg={{output.stdout}}

    - name: Update env
      shell: docker exec -t nginx-filebeat bash -c 'echo JAVA_HOME=$(find /usr/lib/jvm/ -name "*openjdk*" -type d) >> /etc/environment'
      register: output
    - debug: msg={{output.stdout}}

    - name: Add repo
      shell: docker exec -t nginx-filebeat bash -c 'wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch |  apt-key add -;echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" > /etc/apt/sources.list.d/elastic-5.x.list'
      register: output
    - debug: msg={{output.stdout}}
      
    - name: Install Filebeat
      shell: docker exec -t nginx-filebeat bash -c 'apt install filebeat -y'
      register: output
    - debug: msg={{output.stdout}}

    - name: Copy filebeat.yml
      shell: docker cp ./filebeat.yml nginx-filebeat:/etc/filebeat/filebeat.yml
      register: output
    - debug: msg={{output.stdout}}

    - name: Restart NGINX and FILEBEAT
      shell: docker exec -t nginx-filebeat bash -c 'chown root:root /etc/filebeat/filebeat.yml;service nginx restart;service filebeat restart'
      register: output
    - debug: msg={{output.stdout}}
